from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 523)
        MainWindow.setMinimumSize(QSize(435, 523))
        MainWindow.setMaximumSize(QSize(435, 523))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 201, 16))
        self.label_7.setObjectName("label_7")
        self.btn_listo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_listo.setGeometry(QtCore.QRect(350, 20, 61, 28))
        self.btn_listo.setObjectName("btn_listo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_2.setObjectName("label_2")
        self.tb_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_ip.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.tb_ip.setObjectName("tb_ip")
        self.tb_ip.setMaxLength(15)
        self.tb_ip.setAlignment(QtCore.Qt.AlignHCenter)
        self.tb_mascara = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_mascara.setGeometry(QtCore.QRect(230, 110, 181, 27))
        self.tb_mascara.setObjectName("tb_mascara")
        self.tb_mascara.setText("255.255.255.0")
        self.tb_mascara.setMaxLength(15)
        self.tb_mascara.setAlignment(QtCore.Qt.AlignHCenter)
        self.tb_puerta = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_puerta.setGeometry(QtCore.QRect(230, 150, 181, 27))
        self.tb_puerta.setObjectName("tb_puerta")
        self.tb_puerta.setMaxLength(15)
        self.tb_puerta.setAlignment(QtCore.Qt.AlignHCenter)
        self.tb_dns1 = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_dns1.setGeometry(QtCore.QRect(230, 190, 181, 27))
        self.tb_dns1.setObjectName("tb_dns1")
        self.tb_dns1.setMaxLength(15)
        self.tb_dns1.setAlignment(QtCore.Qt.AlignHCenter)
        self.tb_dns2 = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_dns2.setGeometry(QtCore.QRect(230, 230, 181, 27))
        self.tb_dns2.setObjectName("tb_dns2")
        self.tb_dns2.setMaxLength(15)
        self.tb_dns2.setAlignment(QtCore.Qt.AlignHCenter)
        self.tb_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_nombre.setGeometry(QtCore.QRect(10, 30, 181, 27))
        self.tb_nombre.setObjectName("tb_nombre")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 270, 411, 241))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(430, 230, 181, 27))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(430, 150, 181, 27))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(430, 270, 181, 27))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(430, 190, 181, 27))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lbl_proxy_address = QtWidgets.QLabel(self.groupBox)
        self.lbl_proxy_address.setEnabled(False)
        self.lbl_proxy_address.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.lbl_proxy_address.setObjectName("lbl_proxy_address")
        self.lbl_port_proxy = QtWidgets.QLabel(self.groupBox)
        self.lbl_port_proxy.setEnabled(False)
        self.lbl_port_proxy.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.lbl_port_proxy.setObjectName("lbl_port_proxy")
        self.tb_ip_proxy = QtWidgets.QLineEdit(self.groupBox)
        self.tb_ip_proxy.setEnabled(False)
        self.tb_ip_proxy.setGeometry(QtCore.QRect(220, 45, 181, 27))
        self.tb_ip_proxy.setObjectName("tb_ip_proxy")
        self.tb_ip_proxy.setMaxLength(15)
        self.tb_ip_proxy.setAlignment(QtCore.Qt.AlignHCenter)
        self.tb_port_proxy = QtWidgets.QLineEdit(self.groupBox)
        self.tb_port_proxy.setEnabled(False)
        self.tb_port_proxy.setGeometry(QtCore.QRect(220, 85, 181, 27))
        self.tb_port_proxy.setObjectName("tb_port_proxy")
        self.tb_port_proxy.setMaxLength(15)
        self.tb_port_proxy.setAlignment(QtCore.Qt.AlignHCenter)
        self.ck_aut = QtWidgets.QCheckBox(self.groupBox)
        self.ck_aut.setGeometry(QtCore.QRect(10, 135, 171, 20))
        self.ck_aut.setCheckable(True)
        self.ck_aut.setChecked(False)
        self.ck_aut.setEnabled(False)
        self.ck_aut.setObjectName("ck_aut")
        self.tb_password = QtWidgets.QLineEdit(self.groupBox)
        self.tb_password.setEnabled(False)
        self.tb_password.setGeometry(QtCore.QRect(220, 200, 181, 27))
        self.tb_password.setObjectName("tb_password")
        self.tb_password.setAlignment(QtCore.Qt.AlignHCenter)
        self.lbl_pass = QtWidgets.QLabel(self.groupBox)
        self.lbl_pass.setEnabled(False)
        self.lbl_pass.setGeometry(QtCore.QRect(10, 205, 121, 16))
        self.lbl_pass.setObjectName("lbl_pass")
        self.lbl_user = QtWidgets.QLabel(self.groupBox)
        self.lbl_user.setEnabled(False)
        self.lbl_user.setGeometry(QtCore.QRect(10, 165, 141, 16))
        self.lbl_user.setObjectName("lbl_user")
        self.tb_name_user = QtWidgets.QLineEdit(self.groupBox)
        self.tb_name_user.setEnabled(False)
        self.tb_name_user.setGeometry(QtCore.QRect(220, 160, 181, 27))
        self.tb_name_user.setObjectName("tb_name_user")
        self.tb_name_user.setAlignment(QtCore.Qt.AlignHCenter)
        self.ck_proxy = QtWidgets.QCheckBox(self.groupBox)
        self.ck_proxy.setGeometry(QtCore.QRect(10, 20, 171, 20))
        self.ck_proxy.setCheckable(True)
        self.ck_proxy.setChecked(False)
        self.ck_proxy.setObjectName("ck_proxy")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nueva configuración"))
        self.label.setText(_translate("MainWindow", "Dirección IP:"))
        self.label_6.setText(_translate("MainWindow", "Máscara de subred:"))
        self.label_8.setText(_translate("MainWindow", "DNS preferido:"))
        self.label_9.setText(_translate("MainWindow", "DNS alternativo:"))
        self.label_7.setText(_translate("MainWindow", "Puerta de enlace predeterminada:"))
        self.btn_listo.setText(_translate("MainWindow", "Listo"))
        self.label_2.setText(_translate("MainWindow", "Nombre para la configuración:"))
        self.groupBox.setTitle(_translate("MainWindow", "Proxy"))
        self.lbl_proxy_address.setText(_translate("MainWindow", "Dirección del servidor:"))
        self.lbl_port_proxy.setText(_translate("MainWindow", "Puerto del servidor:"))
        self.ck_aut.setText(_translate("MainWindow", "Requiere autenticación:"))
        self.lbl_pass.setText(_translate("MainWindow", "Contraseña:"))
        self.lbl_user.setText(_translate("MainWindow", "Nombre de usuario:"))
        self.ck_proxy.setText(_translate("MainWindow", "Configurar proxy:"))
